#include <iostream>
using namespace std;

// Given a long vector of strings, print the strings that contain 
// the strings generated by numeric string str.

string searchIn[] = {
            "prateek", "sneha", "deepak", "arnav", "shikha", "palak",
            "utkarsh", "divyam", "vidhi", "sparsh", "akku"
    };
string table[] = 
        { " ", ".+@$", "abc", "def", "ghi", "jkl" , "mno", "pqrs" , "tuv", "wxyz" };

void generatePermutation(int index,string number,string comb){
    if(index>=number.length()){
        for(int i=0;i<11;i++)
            if(searchIn[i].find(comb)!=string::npos)
                cout<<searchIn[i]<<endl;
    } else {
        int digit = number.at(index)-'0';
        for(int i=0;i<table[digit].length();i++)
            generatePermutation(index+1,number,comb+string(1,table[digit].at(i)));
    }
}

int main(){
    string value;
    cin>>value;
    generatePermutation(0,value,"");
}